/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package deduper.oscar.haglund;

public class Library {

    private Collaborator collaborator;

    public boolean someLibraryMethod() {
        return true;
    }

    public Collaborator collaborate( String anyString ){ return this.collaborator; }
}
